[package]
name = "threatbutt"
version = "0.0.2"
authors = ["Richo Healey <richo@psych0tik.net>"]
license = "MIT"
repository = "https://github.com/richo/threatbutt-rs"
description = "bindings to the threatbutt api"

[dependencies]
hyper = "0.3.*"
url = "*"
